# Тексты README на всех языках. Ключи одинаковые во всех словарях.
T = {}

T["en"] = dict(
    s_fw="tested firmware", s_langs="languages", s_to="to", copied="Address copied",
    tagline="Run classic Android firmware — HTC Sense, TouchWiz, MIUI, AOSP — on a modern phone. No root, no PC.",
    about="AEmulator boots a real Android 2.3–4.4 system image straight from a firmware file you already have: a recovery ZIP, an Odin archive or a Google factory image. It translates the old ARM code with a patched QEMU, emulates the kernel’s binder, draws with your phone’s GPU and plays sound through Android’s audio stack — everything runs inside a normal app.",
    feat_title="Features",
    feats=["Import almost any firmware format: CWM/TWRP ZIP, Samsung Odin `.tar.md5`, Google factory `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Vendor skins work as shipped: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Hardware graphics through the GL bridge, sound, touch and multitouch, network with a modern TLS proxy",
           "Shared memory-card folder for APKs, music and photos",
           "Material 3 Expressive interface in 18 languages",
           "Free and open source (GPL-3.0)"],
    fw_title="Supported firmware",
    fw_intro="Tested on a Xiaomi 15 (Snapdragon 8 Elite, Android 16). Any 32-bit ARM firmware for Android 2.3–4.4 is worth trying — this list only covers images we have checked.",
    c_device="Device", c_android="Android", c_skin="Skin", c_status="Status", c_download="Download",
    st_ok="Works", st_partial="Partly", st_wip="In progress", st_untested="Not tested yet", st_no="Not yet",
    n_sound="sound works", n_bt="Bluetooth app dialog", n_nosound="no sound yet", n_wip="boots to setup, being stabilised",
    n_lollipop="Android 5 is experimental", n_crash="unofficial port crashes", n_arm64="64-bit Android 7 — needs the planned arm64 engine",
    dl_rootfs="ready-to-import archive", dl_factory="Google factory image", dl_odin="Odin package", dl_zip="recovery ZIP", dl_ftf="FTF package",
    fw_legal="Firmware files belong to their manufacturers. Links point to the manufacturers’ servers or public archives; AEmulator does not ship any firmware.",
    start_title="Quick start",
    steps=["Download the APK from [Releases]({repo}/releases) and install it.",
           "Download a firmware from the table above to your phone.",
           "Open AEmulator → **Add firmware** and pick the file. Import takes a few minutes.",
           "Press **Start**. The first boot is slower: the system optimises its apps.",
           "Use the ⋮ menu for volume, power button and logs; the ⚙️ button opens app settings and language."],
    req_title="Requirements",
    reqs=["Android 8.0+ on a 64-bit ARM phone (arm64-v8a)", "About 1–3 GB of free space per firmware", "A recent Snapdragon / Dimensity / Tensor chip is recommended"],
    build_title="Build from source",
    build_text="You need JDK 17, Android SDK 36 and NDK r28. Native guest parts are built with the scripts in `native/*/build.sh`.",
    how_title="How it works",
    how_text="Each guest process runs under a patched user-mode QEMU. A binder daemon replaces the kernel driver, a GL bridge forwards OpenGL ES calls to the phone’s GPU, and small guest libraries (audio HAL, audio policy wrapper, LD_PRELOAD shim) adapt vendor code to the emulator. The importer reads the firmware, finds the init scripts in its boot image and builds a start plan for system services.",
    credits_title="Credits",
    credits_text="AEmulator grew out of the HTC Desire HD and HTC One M7 emulators by [the original author]({orig}) — their engine made this project possible.",
    support_title="Support the project",
    support_text="If AEmulator brought back a phone you loved, you can support development:",
    links_title="Links",
    l_site="Website", l_channel="Telegram channel", l_author="Author", l_orig="Original author",
    license_title="License",
    license_text="GPL-3.0. Android, trademarks and firmware belong to their owners.",
)

T["ru"] = dict(
    s_fw="проверенных прошивок", s_langs="языков", s_to="до", copied="Адрес скопирован",
    tagline="Старые прошивки Android — HTC Sense, TouchWiz, MIUI, AOSP — на современном телефоне. Без root и без ПК.",
    about="AEmulator загружает настоящую систему Android 2.3–4.4 прямо из файла прошивки: ZIP для рекавери, архива Odin или factory-образа Google. Старый ARM-код транслирует доработанный QEMU, binder ядра эмулируется, графика идёт через GPU телефона, звук — через аудиосистему Android. Всё работает внутри обычного приложения.",
    feat_title="Возможности",
    feats=["Импорт почти любых форматов: ZIP для CWM/TWRP, Odin `.tar.md5` от Samsung, factory `.tgz` от Google, `system.img`, OTA `system.new.dat.br`",
           "Оболочки производителей работают как есть: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Аппаратная графика через GL-мост, звук, касания и мультитач, сеть с современным TLS-прокси",
           "Общая папка «карты памяти» для APK, музыки и фото",
           "Интерфейс Material 3 Expressive на 18 языках",
           "Бесплатно и с открытым кодом (GPL-3.0)"],
    fw_title="Поддерживаемые прошивки",
    fw_intro="Проверено на Xiaomi 15 (Snapdragon 8 Elite, Android 16). Пробовать стоит любую 32-битную ARM-прошивку Android 2.3–4.4 — в списке только проверенные нами.",
    c_device="Устройство", c_android="Android", c_skin="Оболочка", c_status="Статус", c_download="Скачать",
    st_ok="Работает", st_partial="Частично", st_wip="В работе", st_untested="Не проверено", st_no="Пока нет",
    n_sound="звук работает", n_bt="окно ошибки Bluetooth", n_nosound="пока без звука", n_wip="доходит до мастера настройки, дорабатывается",
    n_lollipop="Android 5 — экспериментально", n_crash="неофициальный порт падает", n_arm64="64-битный Android 7 — нужен будущий движок arm64",
    dl_rootfs="готовый архив для импорта", dl_factory="factory-образ Google", dl_odin="пакет Odin", dl_zip="ZIP для рекавери", dl_ftf="пакет FTF",
    fw_legal="Файлы прошивок принадлежат производителям. Ссылки ведут на серверы производителей или публичные архивы; AEmulator не содержит прошивок.",
    start_title="Быстрый старт",
    steps=["Скачайте APK из [Releases]({repo}/releases) и установите.",
           "Скачайте прошивку из таблицы выше на телефон.",
           "Откройте AEmulator → **Добавить прошивку** и выберите файл. Импорт занимает несколько минут.",
           "Нажмите **Запустить**. Первая загрузка дольше: система оптимизирует приложения.",
           "Меню ⋮ — громкость, кнопка питания и журнал; кнопка ⚙️ — настройки приложения и язык."],
    req_title="Требования",
    reqs=["Android 8.0+ на 64-битном ARM-телефоне (arm64-v8a)", "Около 1–3 ГБ свободного места на прошивку", "Рекомендуется современный Snapdragon / Dimensity / Tensor"],
    build_title="Сборка из исходников",
    build_text="Нужны JDK 17, Android SDK 36 и NDK r28. Гостевые библиотеки собираются скриптами `native/*/build.sh`.",
    how_title="Как это устроено",
    how_text="Каждый процесс гостя работает под доработанным QEMU в режиме пользователя. Демон binder заменяет драйвер ядра, GL-мост передаёт вызовы OpenGL ES на GPU телефона, а небольшие гостевые библиотеки (звуковой HAL, обёртка audio policy, прослойка LD_PRELOAD) подгоняют код производителей под эмулятор. Импортёр читает прошивку, находит init-скрипты в boot-образе и строит план запуска системных служб.",
    credits_title="Благодарности",
    credits_text="AEmulator вырос из эмуляторов HTC Desire HD и HTC One M7 [первого автора]({orig}) — без его движка проекта бы не было.",
    support_title="Поддержать проект",
    support_text="Если AEmulator вернул вам любимый телефон, можно поддержать разработку:",
    links_title="Ссылки",
    l_site="Сайт", l_channel="Telegram-канал", l_author="Автор", l_orig="Первый автор",
    license_title="Лицензия",
    license_text="GPL-3.0. Android, товарные знаки и прошивки принадлежат их владельцам.",
)

T["uk"] = dict(
    s_fw="перевірених прошивок", s_langs="мов", s_to="до", copied="Адресу скопійовано",
    tagline="Старі прошивки Android — HTC Sense, TouchWiz, MIUI, AOSP — на сучасному телефоні. Без root і без ПК.",
    about="AEmulator завантажує справжню систему Android 2.3–4.4 прямо з файлу прошивки: ZIP для рекавері, архіву Odin або factory-образу Google. Старий ARM-код транслює доопрацьований QEMU, binder ядра емулюється, графіка йде через GPU телефона, звук — через аудіосистему Android. Усе працює всередині звичайного застосунку.",
    feat_title="Можливості",
    feats=["Імпорт майже будь-яких форматів: ZIP для CWM/TWRP, Odin `.tar.md5` від Samsung, factory `.tgz` від Google, `system.img`, OTA `system.new.dat.br`",
           "Оболонки виробників працюють як є: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Апаратна графіка через GL-міст, звук, дотики й мультитач, мережа із сучасним TLS-проксі",
           "Спільна папка «карти пам’яті» для APK, музики й фото",
           "Інтерфейс Material 3 Expressive 18 мовами",
           "Безкоштовно й з відкритим кодом (GPL-3.0)"],
    fw_title="Підтримувані прошивки",
    fw_intro="Перевірено на Xiaomi 15 (Snapdragon 8 Elite, Android 16). Варто пробувати будь-яку 32-бітну ARM-прошивку Android 2.3–4.4 — у списку лише перевірені нами.",
    c_device="Пристрій", c_android="Android", c_skin="Оболонка", c_status="Стан", c_download="Завантажити",
    st_ok="Працює", st_partial="Частково", st_wip="У роботі", st_untested="Не перевірено", st_no="Поки ні",
    n_sound="звук працює", n_bt="вікно помилки Bluetooth", n_nosound="поки без звуку", n_wip="доходить до майстра налаштування, доопрацьовується",
    n_lollipop="Android 5 — експериментально", n_crash="неофіційний порт падає", n_arm64="64-бітний Android 7 — потрібен майбутній рушій arm64",
    dl_rootfs="готовий архів для імпорту", dl_factory="factory-образ Google", dl_odin="пакет Odin", dl_zip="ZIP для рекавері", dl_ftf="пакет FTF",
    fw_legal="Файли прошивок належать виробникам. Посилання ведуть на сервери виробників або публічні архіви; AEmulator не містить прошивок.",
    start_title="Швидкий старт",
    steps=["Завантажте APK з [Releases]({repo}/releases) і встановіть.",
           "Завантажте прошивку з таблиці вище на телефон.",
           "Відкрийте AEmulator → **Додати прошивку** й виберіть файл. Імпорт триває кілька хвилин.",
           "Натисніть **Запустити**. Перше завантаження довше: система оптимізує застосунки.",
           "Меню ⋮ — гучність, кнопка живлення й журнал; кнопка ⚙️ — налаштування й мова."],
    req_title="Вимоги",
    reqs=["Android 8.0+ на 64-бітному ARM-телефоні (arm64-v8a)", "Близько 1–3 ГБ вільного місця на прошивку", "Рекомендовано сучасний Snapdragon / Dimensity / Tensor"],
    build_title="Збирання з вихідного коду",
    build_text="Потрібні JDK 17, Android SDK 36 і NDK r28. Гостьові бібліотеки збираються скриптами `native/*/build.sh`.",
    how_title="Як це влаштовано",
    how_text="Кожен процес гостя працює під доопрацьованим QEMU в режимі користувача. Демон binder замінює драйвер ядра, GL-міст передає виклики OpenGL ES на GPU телефона, а невеликі гостьові бібліотеки (звуковий HAL, обгортка audio policy, прошарок LD_PRELOAD) підлаштовують код виробників під емулятор. Імпортер читає прошивку, знаходить init-скрипти в boot-образі й будує план запуску системних служб.",
    credits_title="Подяки",
    credits_text="AEmulator виріс з емуляторів HTC Desire HD та HTC One M7 [першого автора]({orig}) — без його рушія проєкту б не було.",
    support_title="Підтримати проєкт",
    support_text="Якщо AEmulator повернув вам улюблений телефон, можна підтримати розробку:",
    links_title="Посилання",
    l_site="Сайт", l_channel="Telegram-канал", l_author="Автор", l_orig="Перший автор",
    license_title="Ліцензія",
    license_text="GPL-3.0. Android, торговельні марки й прошивки належать їхнім власникам.",
)

T["de"] = dict(
    s_fw="getestete Firmwares", s_langs="Sprachen", s_to="bis", copied="Adresse kopiert",
    tagline="Klassische Android-Firmware — HTC Sense, TouchWiz, MIUI, AOSP — auf einem modernen Handy. Ohne Root, ohne PC.",
    about="AEmulator startet ein echtes Android-2.3–4.4-System direkt aus einer Firmware-Datei: Recovery-ZIP, Odin-Archiv oder Google-Factory-Image. Der alte ARM-Code läuft über ein angepasstes QEMU, der Binder des Kernels wird emuliert, die Grafik läuft über die GPU des Handys und der Ton über Androids Audiosystem — alles in einer normalen App.",
    feat_title="Funktionen",
    feats=["Import fast aller Formate: CWM/TWRP-ZIP, Samsung Odin `.tar.md5`, Google Factory `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Hersteller-Oberflächen laufen unverändert: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Hardwaregrafik über die GL-Brücke, Ton, Touch und Multitouch, Netzwerk mit modernem TLS-Proxy",
           "Gemeinsamer Speicherkarten-Ordner für APKs, Musik und Fotos",
           "Material-3-Expressive-Oberfläche in 18 Sprachen",
           "Kostenlos und quelloffen (GPL-3.0)"],
    fw_title="Unterstützte Firmware",
    fw_intro="Getestet auf einem Xiaomi 15 (Snapdragon 8 Elite, Android 16). Jede 32-Bit-ARM-Firmware für Android 2.3–4.4 ist einen Versuch wert — die Liste enthält nur von uns geprüfte Images.",
    c_device="Gerät", c_android="Android", c_skin="Oberfläche", c_status="Status", c_download="Download",
    st_ok="Läuft", st_partial="Teilweise", st_wip="In Arbeit", st_untested="Noch nicht getestet", st_no="Noch nicht",
    n_sound="Ton funktioniert", n_bt="Bluetooth-Fehlerdialog", n_nosound="noch kein Ton", n_wip="startet bis zur Einrichtung, wird stabilisiert",
    n_lollipop="Android 5 ist experimentell", n_crash="inoffizieller Port stürzt ab", n_arm64="64-Bit-Android 7 — braucht die geplante arm64-Engine",
    dl_rootfs="importfertiges Archiv", dl_factory="Google-Factory-Image", dl_odin="Odin-Paket", dl_zip="Recovery-ZIP", dl_ftf="FTF-Paket",
    fw_legal="Firmware-Dateien gehören ihren Herstellern. Links führen zu Herstellerservern oder öffentlichen Archiven; AEmulator enthält keine Firmware.",
    start_title="Schnellstart",
    steps=["APK unter [Releases]({repo}/releases) herunterladen und installieren.",
           "Eine Firmware aus der Tabelle oben aufs Handy laden.",
           "AEmulator öffnen → **Firmware hinzufügen** und die Datei wählen. Der Import dauert einige Minuten.",
           "**Starten** drücken. Der erste Start dauert länger: Das System optimiert Apps.",
           "Menü ⋮ für Lautstärke, Ein/Aus und Protokoll; ⚙️ öffnet Einstellungen und Sprache."],
    req_title="Voraussetzungen",
    reqs=["Android 8.0+ auf einem 64-Bit-ARM-Handy (arm64-v8a)", "Etwa 1–3 GB freier Speicher pro Firmware", "Empfohlen: aktueller Snapdragon / Dimensity / Tensor"],
    build_title="Aus dem Quellcode bauen",
    build_text="Benötigt werden JDK 17, Android SDK 36 und NDK r28. Die Gast-Bibliotheken werden mit `native/*/build.sh` gebaut.",
    how_title="So funktioniert es",
    how_text="Jeder Gastprozess läuft unter einem angepassten User-Mode-QEMU. Ein Binder-Daemon ersetzt den Kernel-Treiber, eine GL-Brücke leitet OpenGL-ES-Aufrufe an die GPU weiter, und kleine Gast-Bibliotheken (Audio-HAL, Audio-Policy-Wrapper, LD_PRELOAD-Shim) passen Herstellercode an den Emulator an. Der Importer liest die Firmware, findet die Init-Skripte im Boot-Image und erstellt einen Startplan für die Systemdienste.",
    credits_title="Dank",
    credits_text="AEmulator ist aus den Emulatoren für HTC Desire HD und HTC One M7 [des Originalautors]({orig}) hervorgegangen — ohne seine Engine gäbe es dieses Projekt nicht.",
    support_title="Projekt unterstützen",
    support_text="Wenn AEmulator dir ein geliebtes Handy zurückgebracht hat, kannst du die Entwicklung unterstützen:",
    links_title="Links",
    l_site="Website", l_channel="Telegram-Kanal", l_author="Autor", l_orig="Originalautor",
    license_title="Lizenz",
    license_text="GPL-3.0. Android, Marken und Firmware gehören ihren Inhabern.",
)

T["fr"] = dict(
    s_fw="ROM testées", s_langs="langues", s_to="à", copied="Adresse copiée",
    tagline="Les anciennes ROM Android — HTC Sense, TouchWiz, MIUI, AOSP — sur un téléphone moderne. Sans root, sans PC.",
    about="AEmulator démarre un vrai système Android 2.3–4.4 directement depuis un fichier de ROM : ZIP recovery, archive Odin ou image d’usine Google. L’ancien code ARM passe par un QEMU modifié, le binder du noyau est émulé, les graphismes utilisent le GPU du téléphone et le son passe par la pile audio d’Android — le tout dans une application ordinaire.",
    feat_title="Fonctionnalités",
    feats=["Import de presque tous les formats : ZIP CWM/TWRP, Odin `.tar.md5` de Samsung, image d’usine Google `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Les surcouches constructeur fonctionnent telles quelles : HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Graphismes matériels via le pont GL, son, tactile et multitouch, réseau avec proxy TLS moderne",
           "Dossier de carte mémoire partagé pour les APK, la musique et les photos",
           "Interface Material 3 Expressive en 18 langues",
           "Gratuit et open source (GPL-3.0)"],
    fw_title="ROM prises en charge",
    fw_intro="Testé sur un Xiaomi 15 (Snapdragon 8 Elite, Android 16). Toute ROM ARM 32 bits pour Android 2.3–4.4 mérite un essai — la liste ne contient que les images vérifiées.",
    c_device="Appareil", c_android="Android", c_skin="Surcouche", c_status="État", c_download="Téléchargement",
    st_ok="Fonctionne", st_partial="Partiel", st_wip="En cours", st_untested="Pas encore testé", st_no="Pas encore",
    n_sound="le son fonctionne", n_bt="boîte d’erreur Bluetooth", n_nosound="pas encore de son", n_wip="démarre jusqu’à l’assistant, en stabilisation",
    n_lollipop="Android 5 est expérimental", n_crash="le portage non officiel plante", n_arm64="Android 7 64 bits — nécessite le futur moteur arm64",
    dl_rootfs="archive prête à importer", dl_factory="image d’usine Google", dl_odin="paquet Odin", dl_zip="ZIP recovery", dl_ftf="paquet FTF",
    fw_legal="Les ROM appartiennent à leurs constructeurs. Les liens mènent aux serveurs des constructeurs ou à des archives publiques ; AEmulator ne contient aucune ROM.",
    start_title="Démarrage rapide",
    steps=["Téléchargez l’APK depuis [Releases]({repo}/releases) et installez-le.",
           "Téléchargez une ROM du tableau ci-dessus sur le téléphone.",
           "Ouvrez AEmulator → **Ajouter une ROM** et choisissez le fichier. L’import prend quelques minutes.",
           "Appuyez sur **Démarrer**. Le premier démarrage est plus long : le système optimise les applis.",
           "Menu ⋮ pour le volume, le bouton marche et le journal ; ⚙️ ouvre les paramètres et la langue."],
    req_title="Configuration requise",
    reqs=["Android 8.0+ sur un téléphone ARM 64 bits (arm64-v8a)", "Environ 1–3 Go libres par ROM", "Puce récente conseillée : Snapdragon / Dimensity / Tensor"],
    build_title="Compiler depuis les sources",
    build_text="Il faut JDK 17, Android SDK 36 et NDK r28. Les bibliothèques invitées se compilent avec `native/*/build.sh`.",
    how_title="Fonctionnement",
    how_text="Chaque processus invité tourne sous un QEMU en mode utilisateur modifié. Un démon binder remplace le pilote du noyau, un pont GL transmet les appels OpenGL ES au GPU, et de petites bibliothèques invitées (HAL audio, enveloppe audio policy, shim LD_PRELOAD) adaptent le code constructeur à l’émulateur. L’importateur lit la ROM, trouve les scripts init dans l’image boot et construit le plan de démarrage des services.",
    credits_title="Remerciements",
    credits_text="AEmulator est né des émulateurs HTC Desire HD et HTC One M7 de [l’auteur d’origine]({orig}) — sans son moteur, ce projet n’existerait pas.",
    support_title="Soutenir le projet",
    support_text="Si AEmulator vous a rendu un téléphone que vous aimiez, vous pouvez soutenir le développement :",
    links_title="Liens",
    l_site="Site web", l_channel="Chaîne Telegram", l_author="Auteur", l_orig="Auteur d’origine",
    license_title="Licence",
    license_text="GPL-3.0. Android, les marques et les ROM appartiennent à leurs propriétaires.",
)

T["es"] = dict(
    s_fw="firmwares probados", s_langs="idiomas", s_to="a", copied="Dirección copiada",
    tagline="Firmware clásico de Android — HTC Sense, TouchWiz, MIUI, AOSP — en un teléfono moderno. Sin root, sin PC.",
    about="AEmulator arranca un sistema Android 2.3–4.4 real directamente desde un archivo de firmware: ZIP de recovery, archivo de Odin o imagen de fábrica de Google. El código ARM antiguo se traduce con un QEMU modificado, el binder del kernel se emula, los gráficos usan la GPU del teléfono y el sonido pasa por la pila de audio de Android — todo dentro de una app normal.",
    feat_title="Características",
    feats=["Importa casi cualquier formato: ZIP CWM/TWRP, Odin `.tar.md5` de Samsung, imagen de fábrica `.tgz` de Google, `system.img`, OTA `system.new.dat.br`",
           "Las capas de los fabricantes funcionan tal cual: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Gráficos por hardware con el puente GL, sonido, táctil y multitáctil, red con proxy TLS moderno",
           "Carpeta compartida de tarjeta de memoria para APK, música y fotos",
           "Interfaz Material 3 Expressive en 18 idiomas",
           "Gratis y de código abierto (GPL-3.0)"],
    fw_title="Firmware compatible",
    fw_intro="Probado en un Xiaomi 15 (Snapdragon 8 Elite, Android 16). Vale la pena probar cualquier firmware ARM de 32 bits para Android 2.3–4.4; la lista solo incluye imágenes comprobadas.",
    c_device="Dispositivo", c_android="Android", c_skin="Capa", c_status="Estado", c_download="Descarga",
    st_ok="Funciona", st_partial="Parcial", st_wip="En progreso", st_untested="Sin probar", st_no="Aún no",
    n_sound="el sonido funciona", n_bt="diálogo de error de Bluetooth", n_nosound="aún sin sonido", n_wip="arranca hasta el asistente, en estabilización",
    n_lollipop="Android 5 es experimental", n_crash="el port no oficial falla", n_arm64="Android 7 de 64 bits — requiere el futuro motor arm64",
    dl_rootfs="archivo listo para importar", dl_factory="imagen de fábrica de Google", dl_odin="paquete Odin", dl_zip="ZIP de recovery", dl_ftf="paquete FTF",
    fw_legal="Los archivos de firmware pertenecen a sus fabricantes. Los enlaces llevan a servidores de fabricantes o archivos públicos; AEmulator no incluye firmware.",
    start_title="Inicio rápido",
    steps=["Descarga el APK desde [Releases]({repo}/releases) e instálalo.",
           "Descarga un firmware de la tabla anterior en el teléfono.",
           "Abre AEmulator → **Añadir firmware** y elige el archivo. La importación tarda unos minutos.",
           "Pulsa **Iniciar**. El primer arranque es más lento: el sistema optimiza las apps.",
           "Menú ⋮ para volumen, botón de encendido y registro; ⚙️ abre ajustes e idioma."],
    req_title="Requisitos",
    reqs=["Android 8.0+ en un teléfono ARM de 64 bits (arm64-v8a)", "Unos 1–3 GB libres por firmware", "Se recomienda un Snapdragon / Dimensity / Tensor reciente"],
    build_title="Compilar desde el código",
    build_text="Necesitas JDK 17, Android SDK 36 y NDK r28. Las bibliotecas del invitado se compilan con `native/*/build.sh`.",
    how_title="Cómo funciona",
    how_text="Cada proceso invitado se ejecuta con un QEMU de modo usuario modificado. Un demonio binder sustituye al controlador del kernel, un puente GL envía las llamadas OpenGL ES a la GPU y pequeñas bibliotecas invitadas (HAL de audio, envoltorio de audio policy, shim LD_PRELOAD) adaptan el código del fabricante al emulador. El importador lee el firmware, encuentra los scripts init en la imagen boot y crea el plan de arranque de los servicios.",
    credits_title="Créditos",
    credits_text="AEmulator nació de los emuladores de HTC Desire HD y HTC One M7 del [autor original]({orig}); sin su motor este proyecto no existiría.",
    support_title="Apoya el proyecto",
    support_text="Si AEmulator te devolvió un teléfono querido, puedes apoyar el desarrollo:",
    links_title="Enlaces",
    l_site="Sitio web", l_channel="Canal de Telegram", l_author="Autor", l_orig="Autor original",
    license_title="Licencia",
    license_text="GPL-3.0. Android, las marcas y el firmware pertenecen a sus dueños.",
)

T["pt-BR"] = dict(
    s_fw="firmwares testados", s_langs="idiomas", s_to="a", copied="Endereço copiado",
    tagline="Firmwares clássicos do Android — HTC Sense, TouchWiz, MIUI, AOSP — em um celular moderno. Sem root, sem PC.",
    about="O AEmulator inicia um sistema Android 2.3–4.4 real direto de um arquivo de firmware: ZIP de recovery, pacote do Odin ou imagem de fábrica do Google. O código ARM antigo é traduzido por um QEMU modificado, o binder do kernel é emulado, os gráficos usam a GPU do celular e o som passa pelo áudio do Android — tudo dentro de um app comum.",
    feat_title="Recursos",
    feats=["Importa quase qualquer formato: ZIP CWM/TWRP, Odin `.tar.md5` da Samsung, imagem de fábrica `.tgz` do Google, `system.img`, OTA `system.new.dat.br`",
           "Interfaces das fabricantes funcionam como vieram: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Gráficos por hardware pela ponte GL, som, toque e multitoque, rede com proxy TLS moderno",
           "Pasta compartilhada de cartão de memória para APKs, músicas e fotos",
           "Interface Material 3 Expressive em 18 idiomas",
           "Gratuito e de código aberto (GPL-3.0)"],
    fw_title="Firmwares compatíveis",
    fw_intro="Testado em um Xiaomi 15 (Snapdragon 8 Elite, Android 16). Vale tentar qualquer firmware ARM de 32 bits do Android 2.3–4.4; a lista traz só imagens verificadas.",
    c_device="Aparelho", c_android="Android", c_skin="Interface", c_status="Status", c_download="Download",
    st_ok="Funciona", st_partial="Parcial", st_wip="Em andamento", st_untested="Não testado", st_no="Ainda não",
    n_sound="som funciona", n_bt="janela de erro do Bluetooth", n_nosound="ainda sem som", n_wip="inicia até a configuração, em estabilização",
    n_lollipop="Android 5 é experimental", n_crash="port não oficial trava", n_arm64="Android 7 64 bits — requer o futuro motor arm64",
    dl_rootfs="arquivo pronto para importar", dl_factory="imagem de fábrica do Google", dl_odin="pacote Odin", dl_zip="ZIP de recovery", dl_ftf="pacote FTF",
    fw_legal="Os firmwares pertencem às fabricantes. Os links levam aos servidores delas ou a arquivos públicos; o AEmulator não inclui firmwares.",
    start_title="Início rápido",
    steps=["Baixe o APK em [Releases]({repo}/releases) e instale.",
           "Baixe um firmware da tabela acima no celular.",
           "Abra o AEmulator → **Adicionar firmware** e escolha o arquivo. A importação leva alguns minutos.",
           "Toque em **Iniciar**. A primeira inicialização é mais lenta: o sistema otimiza os apps.",
           "Menu ⋮ para volume, botão liga/desliga e registro; ⚙️ abre configurações e idioma."],
    req_title="Requisitos",
    reqs=["Android 8.0+ em celular ARM de 64 bits (arm64-v8a)", "Cerca de 1–3 GB livres por firmware", "Recomendado: Snapdragon / Dimensity / Tensor recente"],
    build_title="Compilar do código-fonte",
    build_text="É preciso JDK 17, Android SDK 36 e NDK r28. As bibliotecas do convidado são compiladas com `native/*/build.sh`.",
    how_title="Como funciona",
    how_text="Cada processo convidado roda num QEMU de modo usuário modificado. Um daemon binder substitui o driver do kernel, uma ponte GL envia as chamadas OpenGL ES para a GPU e pequenas bibliotecas (HAL de áudio, wrapper de audio policy, shim LD_PRELOAD) adaptam o código das fabricantes ao emulador. O importador lê o firmware, acha os scripts init na imagem boot e monta o plano de início dos serviços.",
    credits_title="Créditos",
    credits_text="O AEmulator nasceu dos emuladores de HTC Desire HD e HTC One M7 do [autor original]({orig}) — sem o motor dele este projeto não existiria.",
    support_title="Apoie o projeto",
    support_text="Se o AEmulator trouxe de volta um celular querido, você pode apoiar o desenvolvimento:",
    links_title="Links",
    l_site="Site", l_channel="Canal no Telegram", l_author="Autor", l_orig="Autor original",
    license_title="Licença",
    license_text="GPL-3.0. Android, marcas e firmwares pertencem aos seus donos.",
)

T["it"] = dict(
    s_fw="firmware testati", s_langs="lingue", s_to="a", copied="Indirizzo copiato",
    tagline="Firmware Android classici — HTC Sense, TouchWiz, MIUI, AOSP — su un telefono moderno. Senza root, senza PC.",
    about="AEmulator avvia un vero sistema Android 2.3–4.4 direttamente da un file firmware: ZIP per recovery, archivio Odin o immagine di fabbrica Google. Il vecchio codice ARM passa da un QEMU modificato, il binder del kernel è emulato, la grafica usa la GPU del telefono e l’audio passa per lo stack audio di Android — tutto in una normale app.",
    feat_title="Funzionalità",
    feats=["Importa quasi ogni formato: ZIP CWM/TWRP, Odin `.tar.md5` di Samsung, immagine di fabbrica Google `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Le interfacce dei produttori funzionano così come sono: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Grafica hardware tramite il ponte GL, audio, tocco e multitouch, rete con proxy TLS moderno",
           "Cartella condivisa della scheda di memoria per APK, musica e foto",
           "Interfaccia Material 3 Expressive in 18 lingue",
           "Gratuito e open source (GPL-3.0)"],
    fw_title="Firmware supportati",
    fw_intro="Testato su Xiaomi 15 (Snapdragon 8 Elite, Android 16). Vale la pena provare qualsiasi firmware ARM a 32 bit per Android 2.3–4.4; l’elenco contiene solo immagini verificate.",
    c_device="Dispositivo", c_android="Android", c_skin="Interfaccia", c_status="Stato", c_download="Download",
    st_ok="Funziona", st_partial="Parziale", st_wip="In corso", st_untested="Non testato", st_no="Non ancora",
    n_sound="audio funzionante", n_bt="finestra di errore Bluetooth", n_nosound="ancora senza audio", n_wip="si avvia fino alla configurazione, in stabilizzazione",
    n_lollipop="Android 5 è sperimentale", n_crash="il port non ufficiale va in crash", n_arm64="Android 7 a 64 bit — serve il futuro motore arm64",
    dl_rootfs="archivio pronto da importare", dl_factory="immagine di fabbrica Google", dl_odin="pacchetto Odin", dl_zip="ZIP per recovery", dl_ftf="pacchetto FTF",
    fw_legal="I firmware appartengono ai produttori. I link portano ai server dei produttori o ad archivi pubblici; AEmulator non include firmware.",
    start_title="Avvio rapido",
    steps=["Scarica l’APK da [Releases]({repo}/releases) e installalo.",
           "Scarica sul telefono un firmware dalla tabella sopra.",
           "Apri AEmulator → **Aggiungi firmware** e scegli il file. L’importazione richiede qualche minuto.",
           "Premi **Avvia**. Il primo avvio è più lento: il sistema ottimizza le app.",
           "Menu ⋮ per volume, tasto di accensione e registro; ⚙️ apre impostazioni e lingua."],
    req_title="Requisiti",
    reqs=["Android 8.0+ su telefono ARM a 64 bit (arm64-v8a)", "Circa 1–3 GB liberi per firmware", "Consigliato: Snapdragon / Dimensity / Tensor recente"],
    build_title="Compilare dai sorgenti",
    build_text="Servono JDK 17, Android SDK 36 e NDK r28. Le librerie ospiti si compilano con `native/*/build.sh`.",
    how_title="Come funziona",
    how_text="Ogni processo ospite gira sotto un QEMU user-mode modificato. Un demone binder sostituisce il driver del kernel, un ponte GL inoltra le chiamate OpenGL ES alla GPU e piccole librerie ospiti (HAL audio, wrapper audio policy, shim LD_PRELOAD) adattano il codice dei produttori all’emulatore. L’importatore legge il firmware, trova gli script init nell’immagine boot e crea il piano di avvio dei servizi.",
    credits_title="Ringraziamenti",
    credits_text="AEmulator nasce dagli emulatori HTC Desire HD e HTC One M7 dell’[autore originale]({orig}); senza il suo motore questo progetto non esisterebbe.",
    support_title="Sostieni il progetto",
    support_text="Se AEmulator ti ha ridato un telefono amato, puoi sostenere lo sviluppo:",
    links_title="Link",
    l_site="Sito web", l_channel="Canale Telegram", l_author="Autore", l_orig="Autore originale",
    license_title="Licenza",
    license_text="GPL-3.0. Android, i marchi e i firmware appartengono ai rispettivi proprietari.",
)

T["pl"] = dict(
    s_fw="przetestowanych firmware", s_langs="języków", s_to="do", copied="Skopiowano adres",
    tagline="Klasyczne firmware Androida — HTC Sense, TouchWiz, MIUI, AOSP — na nowoczesnym telefonie. Bez roota, bez PC.",
    about="AEmulator uruchamia prawdziwy system Android 2.3–4.4 prosto z pliku firmware: ZIP do recovery, archiwum Odin lub obraz fabryczny Google. Stary kod ARM tłumaczy zmodyfikowane QEMU, binder jądra jest emulowany, grafika korzysta z GPU telefonu, a dźwięk z systemu audio Androida — wszystko w zwykłej aplikacji.",
    feat_title="Funkcje",
    feats=["Import niemal każdego formatu: ZIP CWM/TWRP, Odin `.tar.md5` Samsunga, obraz fabryczny Google `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Nakładki producentów działają bez zmian: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Sprzętowa grafika przez mostek GL, dźwięk, dotyk i multitouch, sieć z nowoczesnym proxy TLS",
           "Wspólny folder karty pamięci na APK, muzykę i zdjęcia",
           "Interfejs Material 3 Expressive w 18 językach",
           "Za darmo i open source (GPL-3.0)"],
    fw_title="Obsługiwane firmware",
    fw_intro="Testowane na Xiaomi 15 (Snapdragon 8 Elite, Android 16). Warto spróbować dowolnego 32-bitowego firmware ARM dla Androida 2.3–4.4; lista zawiera tylko sprawdzone obrazy.",
    c_device="Urządzenie", c_android="Android", c_skin="Nakładka", c_status="Stan", c_download="Pobierz",
    st_ok="Działa", st_partial="Częściowo", st_wip="W toku", st_untested="Nietestowane", st_no="Jeszcze nie",
    n_sound="dźwięk działa", n_bt="okno błędu Bluetooth", n_nosound="na razie bez dźwięku", n_wip="dochodzi do kreatora, stabilizacja trwa",
    n_lollipop="Android 5 eksperymentalnie", n_crash="nieoficjalny port się wysypuje", n_arm64="64-bitowy Android 7 — wymaga planowanego silnika arm64",
    dl_rootfs="archiwum gotowe do importu", dl_factory="obraz fabryczny Google", dl_odin="pakiet Odin", dl_zip="ZIP do recovery", dl_ftf="pakiet FTF",
    fw_legal="Pliki firmware należą do producentów. Linki prowadzą do serwerów producentów lub publicznych archiwów; AEmulator nie zawiera firmware.",
    start_title="Szybki start",
    steps=["Pobierz APK z [Releases]({repo}/releases) i zainstaluj.",
           "Pobierz na telefon firmware z tabeli powyżej.",
           "Otwórz AEmulator → **Dodaj firmware** i wybierz plik. Import trwa kilka minut.",
           "Naciśnij **Uruchom**. Pierwszy start trwa dłużej: system optymalizuje aplikacje.",
           "Menu ⋮ — głośność, przycisk zasilania i dziennik; ⚙️ — ustawienia i język."],
    req_title="Wymagania",
    reqs=["Android 8.0+ na 64-bitowym telefonie ARM (arm64-v8a)", "Około 1–3 GB wolnego miejsca na firmware", "Zalecany nowy Snapdragon / Dimensity / Tensor"],
    build_title="Budowanie ze źródeł",
    build_text="Potrzebne są JDK 17, Android SDK 36 i NDK r28. Biblioteki gościa buduje się skryptami `native/*/build.sh`.",
    how_title="Jak to działa",
    how_text="Każdy proces gościa działa pod zmodyfikowanym QEMU w trybie użytkownika. Demon binder zastępuje sterownik jądra, mostek GL przekazuje wywołania OpenGL ES do GPU, a małe biblioteki gościa (HAL audio, nakładka audio policy, shim LD_PRELOAD) dopasowują kod producentów do emulatora. Importer czyta firmware, znajduje skrypty init w obrazie boot i tworzy plan startu usług.",
    credits_title="Podziękowania",
    credits_text="AEmulator wyrósł z emulatorów HTC Desire HD i HTC One M7 [pierwotnego autora]({orig}) — bez jego silnika tego projektu by nie było.",
    support_title="Wesprzyj projekt",
    support_text="Jeśli AEmulator przywrócił ci ulubiony telefon, możesz wesprzeć rozwój:",
    links_title="Linki",
    l_site="Strona", l_channel="Kanał Telegram", l_author="Autor", l_orig="Pierwotny autor",
    license_title="Licencja",
    license_text="GPL-3.0. Android, znaki towarowe i firmware należą do ich właścicieli.",
)

T["tr"] = dict(
    s_fw="test edilen yazılım", s_langs="dil", s_to="–", copied="Adres kopyalandı",
    tagline="Klasik Android yazılımları — HTC Sense, TouchWiz, MIUI, AOSP — modern bir telefonda. Root ve PC gerekmez.",
    about="AEmulator gerçek bir Android 2.3–4.4 sistemini doğrudan yazılım dosyasından başlatır: recovery ZIP, Odin arşivi veya Google fabrika imajı. Eski ARM kodu değiştirilmiş QEMU ile çevrilir, çekirdeğin binder’ı taklit edilir, grafikler telefonun GPU’sunu, ses Android’in ses altyapısını kullanır — hepsi sıradan bir uygulamanın içinde.",
    feat_title="Özellikler",
    feats=["Neredeyse her biçimi içe aktarma: CWM/TWRP ZIP, Samsung Odin `.tar.md5`, Google fabrika `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Üretici arayüzleri olduğu gibi çalışır: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "GL köprüsüyle donanım grafikleri, ses, dokunma ve çoklu dokunma, modern TLS vekilli ağ",
           "APK, müzik ve fotoğraflar için ortak hafıza kartı klasörü",
           "18 dilde Material 3 Expressive arayüz",
           "Ücretsiz ve açık kaynak (GPL-3.0)"],
    fw_title="Desteklenen yazılımlar",
    fw_intro="Xiaomi 15 (Snapdragon 8 Elite, Android 16) üzerinde test edildi. Android 2.3–4.4 için her 32 bit ARM yazılımı denemeye değer; listede yalnızca doğrulanan imajlar var.",
    c_device="Cihaz", c_android="Android", c_skin="Arayüz", c_status="Durum", c_download="İndir",
    st_ok="Çalışıyor", st_partial="Kısmen", st_wip="Üzerinde çalışılıyor", st_untested="Henüz denenmedi", st_no="Henüz değil",
    n_sound="ses çalışıyor", n_bt="Bluetooth hata penceresi", n_nosound="henüz ses yok", n_wip="kurulum sihirbazına kadar açılıyor, kararlı hâle getiriliyor",
    n_lollipop="Android 5 deneysel", n_crash="resmî olmayan port çöküyor", n_arm64="64 bit Android 7 — planlanan arm64 motoru gerekli",
    dl_rootfs="içe aktarmaya hazır arşiv", dl_factory="Google fabrika imajı", dl_odin="Odin paketi", dl_zip="recovery ZIP", dl_ftf="FTF paketi",
    fw_legal="Yazılım dosyaları üreticilerine aittir. Bağlantılar üretici sunucularına veya herkese açık arşivlere gider; AEmulator hiçbir yazılım içermez.",
    start_title="Hızlı başlangıç",
    steps=["APK’yı [Releases]({repo}/releases) sayfasından indirip kurun.",
           "Yukarıdaki tablodan bir yazılımı telefona indirin.",
           "AEmulator’ı açın → **Yazılım ekle** ve dosyayı seçin. İçe aktarma birkaç dakika sürer.",
           "**Başlat**’a basın. İlk açılış daha uzundur: sistem uygulamaları optimize eder.",
           "⋮ menüsü: ses, güç düğmesi ve günlük; ⚙️ ayarları ve dili açar."],
    req_title="Gereksinimler",
    reqs=["64 bit ARM telefonda Android 8.0+ (arm64-v8a)", "Yazılım başına yaklaşık 1–3 GB boş alan", "Önerilen: yeni bir Snapdragon / Dimensity / Tensor"],
    build_title="Kaynaktan derleme",
    build_text="JDK 17, Android SDK 36 ve NDK r28 gerekir. Misafir kütüphaneleri `native/*/build.sh` betikleriyle derlenir.",
    how_title="Nasıl çalışır",
    how_text="Her misafir süreç değiştirilmiş kullanıcı kipi QEMU altında çalışır. Bir binder arka plan programı çekirdek sürücüsünün yerini alır, GL köprüsü OpenGL ES çağrılarını GPU’ya iletir, küçük misafir kütüphaneleri (ses HAL’i, audio policy sarmalayıcısı, LD_PRELOAD katmanı) üretici kodunu emülatöre uyarlar. İçe aktarıcı yazılımı okur, boot imajındaki init betiklerini bulur ve servislerin başlama planını kurar.",
    credits_title="Teşekkürler",
    credits_text="AEmulator, [ilk geliştiricinin]({orig}) HTC Desire HD ve HTC One M7 emülatörlerinden doğdu — onun motoru olmadan bu proje olmazdı.",
    support_title="Projeyi destekleyin",
    support_text="AEmulator sevdiğiniz bir telefonu geri getirdiyse geliştirmeyi destekleyebilirsiniz:",
    links_title="Bağlantılar",
    l_site="Web sitesi", l_channel="Telegram kanalı", l_author="Geliştirici", l_orig="İlk geliştirici",
    license_title="Lisans",
    license_text="GPL-3.0. Android, markalar ve yazılımlar sahiplerine aittir.",
)

T["ar"] = dict(
    s_fw="برامج ثابتة مُختبرة", s_langs="لغة", s_to="إلى", copied="نُسخ العنوان",
    tagline="شغّل برامج أندرويد الكلاسيكية — HTC Sense وTouchWiz وMIUI وAOSP — على هاتف حديث. بلا روت وبلا حاسوب.",
    about="يقلع AEmulator نظام أندرويد 2.3–4.4 حقيقيًا مباشرة من ملف البرنامج الثابت: ملف ZIP للريكفري أو أرشيف Odin أو صورة مصنع Google. تُترجم شفرة ARM القديمة عبر QEMU معدّل، ويُحاكى binder النواة، وتُرسم الواجهة بمعالج رسومات الهاتف ويمر الصوت عبر نظام صوت أندرويد — كل ذلك داخل تطبيق عادي.",
    feat_title="المزايا",
    feats=["استيراد كل الصيغ تقريبًا: ‏ZIP لـ CWM/TWRP، و‏Odin ‏`.tar.md5` من سامسونج، وصورة مصنع Google ‏`.tgz`، و`system.img`، وOTA ‏`system.new.dat.br`",
           "واجهات الشركات تعمل كما هي: HTC Sense وSamsung TouchWiz وMIUI وAOSP",
           "رسوميات عتادية عبر جسر GL، وصوت، ولمس ولمس متعدد، وشبكة مع وكيل TLS حديث",
           "مجلد بطاقة ذاكرة مشترك لملفات APK والموسيقى والصور",
           "واجهة Material 3 Expressive بـ 18 لغة",
           "مجاني ومفتوح المصدر (GPL-3.0)"],
    fw_title="البرامج الثابتة المدعومة",
    fw_intro="اختُبر على Xiaomi 15 ‏(Snapdragon 8 Elite، أندرويد 16). تستحق أي برامج ARM بمعمارية 32 بت لأندرويد 2.3–4.4 التجربة؛ القائمة تضم ما تحققنا منه فقط.",
    c_device="الجهاز", c_android="أندرويد", c_skin="الواجهة", c_status="الحالة", c_download="تنزيل",
    st_ok="يعمل", st_partial="جزئيًا", st_wip="قيد العمل", st_untested="لم يُختبر", st_no="ليس بعد",
    n_sound="الصوت يعمل", n_bt="نافذة خطأ Bluetooth", n_nosound="بلا صوت حاليًا", n_wip="يصل إلى معالج الإعداد، قيد التحسين",
    n_lollipop="أندرويد 5 تجريبي", n_crash="المنفذ غير الرسمي ينهار", n_arm64="أندرويد 7 بمعمارية 64 بت — يحتاج محرك arm64 المخطط له",
    dl_rootfs="أرشيف جاهز للاستيراد", dl_factory="صورة مصنع Google", dl_odin="حزمة Odin", dl_zip="ZIP للريكفري", dl_ftf="حزمة FTF",
    fw_legal="ملفات البرامج الثابتة ملك لشركاتها. الروابط تشير إلى خوادم الشركات أو أرشيفات عامة؛ لا يتضمن AEmulator أي برامج ثابتة.",
    start_title="البدء السريع",
    steps=["نزّل ملف APK من [Releases]({repo}/releases) وثبّته.",
           "نزّل برنامجًا ثابتًا من الجدول أعلاه إلى هاتفك.",
           "افتح AEmulator ← **إضافة برنامج ثابت** واختر الملف. يستغرق الاستيراد بضع دقائق.",
           "اضغط **تشغيل**. الإقلاع الأول أبطأ: النظام يحسّن التطبيقات.",
           "القائمة ⋮ للصوت وزر التشغيل والسجل؛ وزر ⚙️ للإعدادات واللغة."],
    req_title="المتطلبات",
    reqs=["أندرويد 8.0+ على هاتف ARM بمعمارية 64 بت (arm64-v8a)", "نحو 1–3 غيغابايت لكل برنامج ثابت", "يُنصح بمعالج Snapdragon / Dimensity / Tensor حديث"],
    build_title="البناء من المصدر",
    build_text="تحتاج JDK 17 وAndroid SDK 36 وNDK r28. تُبنى مكتبات الضيف عبر `native/*/build.sh`.",
    how_title="كيف يعمل",
    how_text="تعمل كل عملية ضيف تحت QEMU معدّل بوضع المستخدم. يحل خادم binder محل برنامج تشغيل النواة، وينقل جسر GL استدعاءات OpenGL ES إلى معالج الرسومات، وتكيّف مكتبات صغيرة (HAL للصوت، وغلاف audio policy، وطبقة LD_PRELOAD) شفرة الشركات مع المحاكي. يقرأ المستورد البرنامج الثابت ويجد سكربتات init في صورة boot ويبني خطة تشغيل الخدمات.",
    credits_title="شكر وتقدير",
    credits_text="نشأ AEmulator من محاكيات HTC Desire HD وHTC One M7 التي صنعها [المطوّر الأصلي]({orig})، ولولا محركه ما وُجد هذا المشروع.",
    support_title="ادعم المشروع",
    support_text="إن أعاد إليك AEmulator هاتفًا أحببته، يمكنك دعم التطوير:",
    links_title="روابط",
    l_site="الموقع", l_channel="قناة تيليجرام", l_author="المطوّر", l_orig="المطوّر الأصلي",
    license_title="الترخيص",
    license_text="GPL-3.0. أندرويد والعلامات التجارية والبرامج الثابتة ملك لأصحابها.",
)

T["fa"] = dict(
    s_fw="فرم‌ویر آزموده", s_langs="زبان", s_to="تا", copied="نشانی کپی شد",
    tagline="فرم‌ویرهای کلاسیک اندروید — HTC Sense، TouchWiz، MIUI، AOSP — روی گوشی مدرن. بدون روت و بدون رایانه.",
    about="AEmulator یک سیستم واقعی اندروید 2.3 تا 4.4 را مستقیم از فایل فرم‌ویر بوت می‌کند: ZIP ریکاوری، آرشیو Odin یا ایمیج کارخانهٔ گوگل. کد قدیمی ARM با QEMU اصلاح‌شده ترجمه می‌شود، binder هسته شبیه‌سازی می‌شود، گرافیک با GPU گوشی و صدا با سامانهٔ صوتی اندروید پخش می‌شود — همه درون یک برنامهٔ معمولی.",
    feat_title="ویژگی‌ها",
    feats=["درون‌ریزی تقریباً همهٔ قالب‌ها: ‏ZIP ‏CWM/TWRP، ‏Odin ‏`.tar.md5` سامسونگ، ایمیج کارخانهٔ گوگل ‏`.tgz`، ‏`system.img`، ‏OTA ‏`system.new.dat.br`",
           "رابط‌های سازندگان همان‌طور که هستند کار می‌کنند: HTC Sense، Samsung TouchWiz، MIUI، AOSP",
           "گرافیک سخت‌افزاری از طریق پل GL، صدا، لمس و چندلمسی، شبکه با پراکسی TLS مدرن",
           "پوشهٔ مشترک کارت حافظه برای APK، موسیقی و عکس",
           "رابط Material 3 Expressive به 18 زبان",
           "رایگان و متن‌باز (GPL-3.0)"],
    fw_title="فرم‌ویرهای پشتیبانی‌شده",
    fw_intro="روی Xiaomi 15 ‏(Snapdragon 8 Elite، اندروید 16) آزمایش شده است. هر فرم‌ویر ARM ‏32 بیتی اندروید 2.3 تا 4.4 ارزش امتحان دارد؛ فهرست فقط ایمیج‌های بررسی‌شده را دارد.",
    c_device="دستگاه", c_android="اندروید", c_skin="رابط", c_status="وضعیت", c_download="دانلود",
    st_ok="کار می‌کند", st_partial="تا حدی", st_wip="در حال کار", st_untested="هنوز آزمایش نشده", st_no="هنوز نه",
    n_sound="صدا کار می‌کند", n_bt="پنجرهٔ خطای Bluetooth", n_nosound="فعلاً بدون صدا", n_wip="تا راه‌انداز بالا می‌آید، در حال پایدارسازی",
    n_lollipop="اندروید 5 آزمایشی است", n_crash="پورت غیررسمی کرش می‌کند", n_arm64="اندروید 7 ‏64 بیتی — به موتور arm64 آینده نیاز دارد",
    dl_rootfs="آرشیو آمادهٔ درون‌ریزی", dl_factory="ایمیج کارخانهٔ گوگل", dl_odin="بستهٔ Odin", dl_zip="ZIP ریکاوری", dl_ftf="بستهٔ FTF",
    fw_legal="فایل‌های فرم‌ویر متعلق به سازندگان‌اند. پیوندها به سرورهای سازندگان یا بایگانی‌های عمومی می‌روند؛ AEmulator هیچ فرم‌ویری ندارد.",
    start_title="شروع سریع",
    steps=["فایل APK را از [Releases]({repo}/releases) دانلود و نصب کنید.",
           "یک فرم‌ویر از جدول بالا روی گوشی دانلود کنید.",
           "AEmulator را باز کنید ← **افزودن فرم‌ویر** و فایل را انتخاب کنید. درون‌ریزی چند دقیقه طول می‌کشد.",
           "**اجرا** را بزنید. بوت اول کندتر است: سیستم برنامه‌ها را بهینه می‌کند.",
           "منوی ⋮ برای صدا، دکمهٔ پاور و گزارش؛ دکمهٔ ⚙️ برای تنظیمات و زبان."],
    req_title="نیازمندی‌ها",
    reqs=["اندروید 8.0+ روی گوشی ARM ‏64 بیتی (arm64-v8a)", "حدود 1 تا 3 گیگابایت فضای آزاد برای هر فرم‌ویر", "پیشنهاد: Snapdragon / Dimensity / Tensor جدید"],
    build_title="ساخت از کد منبع",
    build_text="به JDK 17، Android SDK 36 و NDK r28 نیاز دارید. کتابخانه‌های مهمان با `native/*/build.sh` ساخته می‌شوند.",
    how_title="چگونه کار می‌کند",
    how_text="هر فرایند مهمان زیر یک QEMU اصلاح‌شده در حالت کاربر اجرا می‌شود. سرویس binder جای درایور هسته را می‌گیرد، پل GL فراخوانی‌های OpenGL ES را به GPU می‌فرستد و کتابخانه‌های کوچک مهمان (HAL صوتی، پوشش audio policy، لایهٔ LD_PRELOAD) کد سازندگان را با شبیه‌ساز سازگار می‌کنند. درون‌ریز فرم‌ویر را می‌خواند، اسکریپت‌های init را در ایمیج boot پیدا می‌کند و برنامهٔ اجرای سرویس‌ها را می‌سازد.",
    credits_title="سپاس",
    credits_text="AEmulator از شبیه‌سازهای HTC Desire HD و HTC One M7 ‏[سازندهٔ نخست]({orig}) رشد کرد — بدون موتور او این پروژه وجود نداشت.",
    support_title="حمایت از پروژه",
    support_text="اگر AEmulator گوشی محبوبتان را برگرداند، می‌توانید از توسعه حمایت کنید:",
    links_title="پیوندها",
    l_site="وب‌سایت", l_channel="کانال تلگرام", l_author="سازنده", l_orig="سازندهٔ نخست",
    license_title="مجوز",
    license_text="GPL-3.0. اندروید، نشان‌های تجاری و فرم‌ویرها متعلق به صاحبانشان‌اند.",
)

T["hi"] = dict(
    s_fw="परखे गए फ़र्मवेयर", s_langs="भाषाएँ", s_to="से", copied="पता कॉपी हुआ",
    tagline="पुराने Android फ़र्मवेयर — HTC Sense, TouchWiz, MIUI, AOSP — आधुनिक फ़ोन पर। बिना root, बिना PC।",
    about="AEmulator सीधे फ़र्मवेयर फ़ाइल से असली Android 2.3–4.4 सिस्टम बूट करता है: रिकवरी ZIP, Odin आर्काइव या Google फ़ैक्टरी इमेज। पुराना ARM कोड संशोधित QEMU से चलता है, कर्नेल का binder एमुलेट होता है, ग्राफ़िक्स फ़ोन के GPU से और आवाज़ Android के ऑडियो सिस्टम से चलती है — सब कुछ एक सामान्य ऐप के भीतर।",
    feat_title="विशेषताएँ",
    feats=["लगभग हर फ़ॉर्मेट आयात करें: CWM/TWRP ZIP, Samsung Odin `.tar.md5`, Google फ़ैक्टरी `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "कंपनियों के स्किन जैसे हैं वैसे चलते हैं: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "GL ब्रिज से हार्डवेयर ग्राफ़िक्स, आवाज़, टच और मल्टीटच, आधुनिक TLS प्रॉक्सी के साथ नेटवर्क",
           "APK, संगीत और फ़ोटो के लिए साझा मेमोरी कार्ड फ़ोल्डर",
           "18 भाषाओं में Material 3 Expressive इंटरफ़ेस",
           "मुफ़्त और ओपन सोर्स (GPL-3.0)"],
    fw_title="समर्थित फ़र्मवेयर",
    fw_intro="Xiaomi 15 (Snapdragon 8 Elite, Android 16) पर परखा गया। Android 2.3–4.4 का कोई भी 32-बिट ARM फ़र्मवेयर आज़माने लायक है; सूची में केवल जाँची गई इमेज हैं।",
    c_device="डिवाइस", c_android="Android", c_skin="स्किन", c_status="स्थिति", c_download="डाउनलोड",
    st_ok="चलता है", st_partial="आंशिक", st_wip="काम जारी", st_untested="अभी परखा नहीं", st_no="अभी नहीं",
    n_sound="आवाज़ काम करती है", n_bt="Bluetooth त्रुटि संवाद", n_nosound="अभी आवाज़ नहीं", n_wip="सेटअप तक बूट होता है, स्थिर किया जा रहा है",
    n_lollipop="Android 5 प्रयोगात्मक", n_crash="अनौपचारिक पोर्ट क्रैश होता है", n_arm64="64-बिट Android 7 — नियोजित arm64 इंजन चाहिए",
    dl_rootfs="आयात के लिए तैयार आर्काइव", dl_factory="Google फ़ैक्टरी इमेज", dl_odin="Odin पैकेज", dl_zip="रिकवरी ZIP", dl_ftf="FTF पैकेज",
    fw_legal="फ़र्मवेयर फ़ाइलें उनके निर्माताओं की हैं। लिंक निर्माताओं के सर्वर या सार्वजनिक आर्काइव पर जाते हैं; AEmulator में कोई फ़र्मवेयर नहीं है।",
    start_title="जल्दी शुरुआत",
    steps=["[Releases]({repo}/releases) से APK डाउनलोड करके इंस्टॉल करें।",
           "ऊपर की तालिका से कोई फ़र्मवेयर फ़ोन पर डाउनलोड करें।",
           "AEmulator खोलें → **फ़र्मवेयर जोड़ें** और फ़ाइल चुनें। आयात में कुछ मिनट लगते हैं।",
           "**चलाएँ** दबाएँ। पहला बूट धीमा होता है: सिस्टम ऐप्स ऑप्टिमाइज़ करता है।",
           "⋮ मेनू में वॉल्यूम, पावर बटन और लॉग; ⚙️ से सेटिंग्स और भाषा।"],
    req_title="आवश्यकताएँ",
    reqs=["64-बिट ARM फ़ोन (arm64-v8a) पर Android 8.0+", "प्रति फ़र्मवेयर लगभग 1–3 GB खाली जगह", "नया Snapdragon / Dimensity / Tensor सुझाया जाता है"],
    build_title="सोर्स से बनाएँ",
    build_text="JDK 17, Android SDK 36 और NDK r28 चाहिए। गेस्ट लाइब्रेरी `native/*/build.sh` से बनती हैं।",
    how_title="यह कैसे काम करता है",
    how_text="हर गेस्ट प्रोसेस संशोधित यूज़र-मोड QEMU में चलता है। एक binder डेमन कर्नेल ड्राइवर की जगह लेता है, GL ब्रिज OpenGL ES कॉल GPU तक भेजता है, और छोटी गेस्ट लाइब्रेरी (ऑडियो HAL, audio policy रैपर, LD_PRELOAD शिम) निर्माताओं के कोड को एमुलेटर के अनुकूल बनाती हैं। इम्पोर्टर फ़र्मवेयर पढ़ता है, boot इमेज में init स्क्रिप्ट ढूँढता है और सेवाओं की शुरुआत की योजना बनाता है।",
    credits_title="आभार",
    credits_text="AEmulator [मूल लेखक]({orig}) के HTC Desire HD और HTC One M7 एमुलेटर से विकसित हुआ — उनके इंजन के बिना यह प्रोजेक्ट नहीं होता।",
    support_title="प्रोजेक्ट का समर्थन करें",
    support_text="अगर AEmulator ने आपका प्यारा फ़ोन लौटा दिया, तो आप विकास में मदद कर सकते हैं:",
    links_title="लिंक",
    l_site="वेबसाइट", l_channel="Telegram चैनल", l_author="लेखक", l_orig="मूल लेखक",
    license_title="लाइसेंस",
    license_text="GPL-3.0। Android, ट्रेडमार्क और फ़र्मवेयर उनके स्वामियों के हैं।",
)

T["id"] = dict(
    s_fw="firmware teruji", s_langs="bahasa", s_to="hingga", copied="Alamat disalin",
    tagline="Firmware Android klasik — HTC Sense, TouchWiz, MIUI, AOSP — di ponsel modern. Tanpa root, tanpa PC.",
    about="AEmulator mem-boot sistem Android 2.3–4.4 asli langsung dari file firmware: ZIP recovery, arsip Odin, atau factory image Google. Kode ARM lama diterjemahkan oleh QEMU yang dimodifikasi, binder kernel diemulasikan, grafis memakai GPU ponsel, dan suara lewat sistem audio Android — semuanya di dalam aplikasi biasa.",
    feat_title="Fitur",
    feats=["Impor hampir semua format: ZIP CWM/TWRP, Odin `.tar.md5` Samsung, factory image Google `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "Tampilan pabrikan berjalan apa adanya: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Grafis hardware lewat jembatan GL, suara, sentuh dan multisentuh, jaringan dengan proxy TLS modern",
           "Folder kartu memori bersama untuk APK, musik, dan foto",
           "Antarmuka Material 3 Expressive dalam 18 bahasa",
           "Gratis dan sumber terbuka (GPL-3.0)"],
    fw_title="Firmware yang didukung",
    fw_intro="Diuji di Xiaomi 15 (Snapdragon 8 Elite, Android 16). Firmware ARM 32-bit apa pun untuk Android 2.3–4.4 layak dicoba; daftar ini hanya memuat image yang sudah kami periksa.",
    c_device="Perangkat", c_android="Android", c_skin="Tampilan", c_status="Status", c_download="Unduh",
    st_ok="Berjalan", st_partial="Sebagian", st_wip="Dikerjakan", st_untested="Belum diuji", st_no="Belum",
    n_sound="suara berfungsi", n_bt="dialog galat Bluetooth", n_nosound="belum ada suara", n_wip="boot sampai penyiapan, sedang distabilkan",
    n_lollipop="Android 5 eksperimental", n_crash="port tidak resmi crash", n_arm64="Android 7 64-bit — perlu mesin arm64 yang direncanakan",
    dl_rootfs="arsip siap impor", dl_factory="factory image Google", dl_odin="paket Odin", dl_zip="ZIP recovery", dl_ftf="paket FTF",
    fw_legal="File firmware milik pabrikannya. Tautan mengarah ke server pabrikan atau arsip publik; AEmulator tidak menyertakan firmware.",
    start_title="Mulai cepat",
    steps=["Unduh APK dari [Releases]({repo}/releases) lalu pasang.",
           "Unduh firmware dari tabel di atas ke ponsel.",
           "Buka AEmulator → **Tambah firmware** lalu pilih file. Impor butuh beberapa menit.",
           "Tekan **Mulai**. Boot pertama lebih lambat: sistem mengoptimalkan aplikasi.",
           "Menu ⋮ untuk volume, tombol daya, dan log; ⚙️ membuka setelan dan bahasa."],
    req_title="Persyaratan",
    reqs=["Android 8.0+ di ponsel ARM 64-bit (arm64-v8a)", "Sekitar 1–3 GB ruang kosong per firmware", "Disarankan Snapdragon / Dimensity / Tensor terbaru"],
    build_title="Membangun dari sumber",
    build_text="Butuh JDK 17, Android SDK 36, dan NDK r28. Pustaka tamu dibangun dengan `native/*/build.sh`.",
    how_title="Cara kerja",
    how_text="Setiap proses tamu berjalan di QEMU mode pengguna yang dimodifikasi. Daemon binder menggantikan driver kernel, jembatan GL meneruskan panggilan OpenGL ES ke GPU, dan pustaka tamu kecil (HAL audio, pembungkus audio policy, shim LD_PRELOAD) menyesuaikan kode pabrikan dengan emulator. Importir membaca firmware, menemukan skrip init di image boot, dan menyusun rencana mulai layanan.",
    credits_title="Kredit",
    credits_text="AEmulator tumbuh dari emulator HTC Desire HD dan HTC One M7 karya [pembuat asli]({orig}) — tanpa mesinnya proyek ini tidak akan ada.",
    support_title="Dukung proyek",
    support_text="Jika AEmulator mengembalikan ponsel kesayangan Anda, Anda bisa mendukung pengembangan:",
    links_title="Tautan",
    l_site="Situs web", l_channel="Kanal Telegram", l_author="Pembuat", l_orig="Pembuat asli",
    license_title="Lisensi",
    license_text="GPL-3.0. Android, merek dagang, dan firmware milik pemiliknya.",
)

T["vi"] = dict(
    s_fw="firmware đã thử", s_langs="ngôn ngữ", s_to="đến", copied="Đã sao chép địa chỉ",
    tagline="Firmware Android cổ điển — HTC Sense, TouchWiz, MIUI, AOSP — trên điện thoại hiện đại. Không root, không cần PC.",
    about="AEmulator khởi động một hệ thống Android 2.3–4.4 thật trực tiếp từ tệp firmware: ZIP recovery, gói Odin hoặc factory image của Google. Mã ARM cũ được dịch bằng QEMU đã chỉnh sửa, binder của nhân được giả lập, đồ họa dùng GPU điện thoại và âm thanh đi qua hệ thống âm thanh Android — tất cả trong một ứng dụng bình thường.",
    feat_title="Tính năng",
    feats=["Nhập gần như mọi định dạng: ZIP CWM/TWRP, Odin `.tar.md5` của Samsung, factory `.tgz` của Google, `system.img`, OTA `system.new.dat.br`",
           "Giao diện hãng chạy nguyên bản: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "Đồ họa phần cứng qua cầu GL, âm thanh, cảm ứng và đa điểm, mạng với proxy TLS hiện đại",
           "Thư mục thẻ nhớ dùng chung cho APK, nhạc và ảnh",
           "Giao diện Material 3 Expressive với 18 ngôn ngữ",
           "Miễn phí và mã nguồn mở (GPL-3.0)"],
    fw_title="Firmware được hỗ trợ",
    fw_intro="Đã thử trên Xiaomi 15 (Snapdragon 8 Elite, Android 16). Mọi firmware ARM 32-bit cho Android 2.3–4.4 đều đáng thử; danh sách chỉ gồm các image đã kiểm tra.",
    c_device="Thiết bị", c_android="Android", c_skin="Giao diện", c_status="Trạng thái", c_download="Tải về",
    st_ok="Chạy tốt", st_partial="Một phần", st_wip="Đang làm", st_untested="Chưa thử", st_no="Chưa",
    n_sound="có âm thanh", n_bt="hộp thoại lỗi Bluetooth", n_nosound="chưa có âm thanh", n_wip="khởi động tới trình thiết lập, đang ổn định",
    n_lollipop="Android 5 là thử nghiệm", n_crash="bản port không chính thức bị lỗi", n_arm64="Android 7 64-bit — cần engine arm64 dự kiến",
    dl_rootfs="gói sẵn để nhập", dl_factory="factory image Google", dl_odin="gói Odin", dl_zip="ZIP recovery", dl_ftf="gói FTF",
    fw_legal="Tệp firmware thuộc về nhà sản xuất. Liên kết dẫn tới máy chủ của hãng hoặc kho lưu trữ công khai; AEmulator không kèm firmware nào.",
    start_title="Bắt đầu nhanh",
    steps=["Tải APK từ [Releases]({repo}/releases) và cài đặt.",
           "Tải một firmware trong bảng trên về điện thoại.",
           "Mở AEmulator → **Thêm firmware** và chọn tệp. Việc nhập mất vài phút.",
           "Nhấn **Chạy**. Lần khởi động đầu chậm hơn: hệ thống tối ưu ứng dụng.",
           "Menu ⋮ để chỉnh âm lượng, nút nguồn và nhật ký; ⚙️ mở cài đặt và ngôn ngữ."],
    req_title="Yêu cầu",
    reqs=["Android 8.0+ trên điện thoại ARM 64-bit (arm64-v8a)", "Khoảng 1–3 GB trống cho mỗi firmware", "Nên dùng Snapdragon / Dimensity / Tensor đời mới"],
    build_title="Biên dịch từ mã nguồn",
    build_text="Cần JDK 17, Android SDK 36 và NDK r28. Thư viện khách được dựng bằng `native/*/build.sh`.",
    how_title="Cách hoạt động",
    how_text="Mỗi tiến trình khách chạy dưới QEMU chế độ người dùng đã chỉnh sửa. Một daemon binder thay cho driver nhân, cầu GL chuyển lệnh OpenGL ES tới GPU và các thư viện khách nhỏ (HAL âm thanh, lớp bọc audio policy, shim LD_PRELOAD) điều chỉnh mã của hãng cho hợp với trình giả lập. Trình nhập đọc firmware, tìm script init trong image boot và lập kế hoạch khởi động dịch vụ.",
    credits_title="Ghi công",
    credits_text="AEmulator phát triển từ trình giả lập HTC Desire HD và HTC One M7 của [tác giả gốc]({orig}) — không có engine của anh ấy thì không có dự án này.",
    support_title="Ủng hộ dự án",
    support_text="Nếu AEmulator mang lại chiếc điện thoại bạn yêu thích, bạn có thể ủng hộ phát triển:",
    links_title="Liên kết",
    l_site="Trang web", l_channel="Kênh Telegram", l_author="Tác giả", l_orig="Tác giả gốc",
    license_title="Giấy phép",
    license_text="GPL-3.0. Android, nhãn hiệu và firmware thuộc về chủ sở hữu.",
)

T["zh-CN"] = dict(
    s_fw="已测试固件", s_langs="种语言", s_to="至", copied="地址已复制",
    tagline="在现代手机上运行经典 Android 固件——HTC Sense、TouchWiz、MIUI、AOSP。无需 root，无需电脑。",
    about="AEmulator 直接从固件文件启动真实的 Android 2.3–4.4 系统：Recovery 卡刷包、Odin 包或 Google 出厂镜像。旧的 ARM 代码由改进的 QEMU 转译，内核 binder 被模拟，图形使用手机 GPU 绘制，声音经由 Android 音频系统播放——一切都在一个普通应用里完成。",
    feat_title="功能",
    feats=["导入几乎所有格式：CWM/TWRP 卡刷 ZIP、三星 Odin `.tar.md5`、Google 出厂 `.tgz`、`system.img`、OTA `system.new.dat.br`",
           "厂商系统原样运行：HTC Sense、三星 TouchWiz、MIUI、AOSP",
           "经 GL 桥的硬件图形、声音、触控与多点触控，带现代 TLS 代理的网络",
           "共享存储卡文件夹，方便放 APK、音乐和照片",
           "Material 3 Expressive 界面，支持 18 种语言",
           "免费开源（GPL-3.0）"],
    fw_title="支持的固件",
    fw_intro="在 Xiaomi 15（骁龙 8 Elite，Android 16）上测试。任何适用于 Android 2.3–4.4 的 32 位 ARM 固件都值得一试；列表仅包含我们验证过的镜像。",
    c_device="设备", c_android="Android", c_skin="系统界面", c_status="状态", c_download="下载",
    st_ok="可用", st_partial="部分可用", st_wip="进行中", st_untested="尚未测试", st_no="暂不支持",
    n_sound="声音正常", n_bt="蓝牙错误弹窗", n_nosound="暂无声音", n_wip="可进入开机向导，正在完善",
    n_lollipop="Android 5 为实验性", n_crash="非官方移植会崩溃", n_arm64="64 位 Android 7——需要规划中的 arm64 引擎",
    dl_rootfs="可直接导入的压缩包", dl_factory="Google 出厂镜像", dl_odin="Odin 包", dl_zip="卡刷 ZIP", dl_ftf="FTF 包",
    fw_legal="固件归各厂商所有。链接指向厂商服务器或公共存档；AEmulator 不附带任何固件。",
    start_title="快速开始",
    steps=["从 [Releases]({repo}/releases) 下载并安装 APK。",
           "把上表中的固件下载到手机。",
           "打开 AEmulator →**添加固件**并选择文件。导入需要几分钟。",
           "点击**启动**。首次启动较慢：系统正在优化应用。",
           "⋮ 菜单可调音量、电源键和日志；⚙️ 打开设置与语言。"],
    req_title="要求",
    reqs=["64 位 ARM 手机（arm64-v8a）上的 Android 8.0+", "每个固件约需 1–3 GB 空间", "推荐较新的骁龙 / 天玑 / Tensor 芯片"],
    build_title="从源码构建",
    build_text="需要 JDK 17、Android SDK 36 和 NDK r28。客户机库通过 `native/*/build.sh` 构建。",
    how_title="工作原理",
    how_text="每个客户机进程运行在改进的用户态 QEMU 中。binder 守护进程取代内核驱动，GL 桥把 OpenGL ES 调用转发给 GPU，小型客户机库（音频 HAL、audio policy 包装、LD_PRELOAD 垫片）让厂商代码适配模拟器。导入器读取固件，在 boot 镜像中找到 init 脚本，并生成系统服务的启动计划。",
    credits_title="致谢",
    credits_text="AEmulator 源自[原作者]({orig})的 HTC Desire HD 与 HTC One M7 模拟器——没有他的引擎就没有本项目。",
    support_title="支持项目",
    support_text="如果 AEmulator 让你心爱的手机重获新生，欢迎支持开发：",
    links_title="链接",
    l_site="网站", l_channel="Telegram 频道", l_author="作者", l_orig="原作者",
    license_title="许可证",
    license_text="GPL-3.0。Android、商标及固件归其所有者所有。",
)

T["ja"] = dict(
    s_fw="検証済みファームウェア", s_langs="言語", s_to="〜", copied="アドレスをコピーしました",
    tagline="懐かしの Android ファームウェア — HTC Sense、TouchWiz、MIUI、AOSP — を最新スマホで。root も PC も不要。",
    about="AEmulator はファームウェアファイルから本物の Android 2.3〜4.4 を直接起動します：リカバリー ZIP、Odin アーカイブ、Google ファクトリーイメージ。古い ARM コードは改良版 QEMU で変換し、カーネルの binder をエミュレートし、描画はスマホの GPU、音声は Android のオーディオを使います。すべて普通のアプリの中で動きます。",
    feat_title="特長",
    feats=["ほぼすべての形式をインポート：CWM/TWRP ZIP、Samsung Odin `.tar.md5`、Google ファクトリー `.tgz`、`system.img`、OTA `system.new.dat.br`",
           "メーカー独自 UI がそのまま動作：HTC Sense、Samsung TouchWiz、MIUI、AOSP",
           "GL ブリッジによるハードウェア描画、音声、タッチとマルチタッチ、最新 TLS プロキシ付きネットワーク",
           "APK・音楽・写真用の共有メモリーカードフォルダー",
           "18 言語対応の Material 3 Expressive UI",
           "無料・オープンソース（GPL-3.0）"],
    fw_title="対応ファームウェア",
    fw_intro="Xiaomi 15（Snapdragon 8 Elite、Android 16）で検証。Android 2.3〜4.4 の 32 ビット ARM ファームウェアなら試す価値があります。一覧は検証済みのイメージのみです。",
    c_device="端末", c_android="Android", c_skin="UI", c_status="状態", c_download="ダウンロード",
    st_ok="動作", st_partial="一部動作", st_wip="対応中", st_untested="未検証", st_no="未対応",
    n_sound="音声あり", n_bt="Bluetooth エラー表示", n_nosound="音声はまだ", n_wip="初期設定まで起動、安定化中",
    n_lollipop="Android 5 は試験的", n_crash="非公式移植版はクラッシュ", n_arm64="64 ビット Android 7 — 予定中の arm64 エンジンが必要",
    dl_rootfs="そのまま取り込めるアーカイブ", dl_factory="Google ファクトリーイメージ", dl_odin="Odin パッケージ", dl_zip="リカバリー ZIP", dl_ftf="FTF パッケージ",
    fw_legal="ファームウェアは各メーカーに帰属します。リンク先はメーカーのサーバーまたは公開アーカイブで、AEmulator にファームウェアは含まれません。",
    start_title="クイックスタート",
    steps=["[Releases]({repo}/releases) から APK をダウンロードしてインストール。",
           "上の表からファームウェアをスマホにダウンロード。",
           "AEmulator を開き →**ファームウェアを追加**でファイルを選択。インポートには数分かかります。",
           "**起動**をタップ。初回はアプリ最適化のため時間がかかります。",
           "⋮ メニューで音量・電源ボタン・ログ、⚙️ で設定と言語。"],
    req_title="動作要件",
    reqs=["64 ビット ARM 端末（arm64-v8a）の Android 8.0+", "ファームウェア 1 つにつき約 1〜3 GB の空き", "最新の Snapdragon / Dimensity / Tensor を推奨"],
    build_title="ソースからビルド",
    build_text="JDK 17、Android SDK 36、NDK r28 が必要です。ゲスト用ライブラリは `native/*/build.sh` でビルドします。",
    how_title="仕組み",
    how_text="各ゲストプロセスは改良版ユーザーモード QEMU で動きます。binder デーモンがカーネルドライバーの代わりを務め、GL ブリッジが OpenGL ES 呼び出しを GPU に転送し、小さなゲストライブラリ（オーディオ HAL、audio policy ラッパー、LD_PRELOAD シム）がメーカーのコードをエミュレーターに合わせます。インポーターはファームウェアを読み、boot イメージの init スクリプトからサービスの起動計画を作ります。",
    credits_title="クレジット",
    credits_text="AEmulator は[オリジナル作者]({orig})の HTC Desire HD・HTC One M7 エミュレーターから生まれました。そのエンジンなしにこのプロジェクトはありません。",
    support_title="プロジェクトを支援",
    support_text="AEmulator で思い出のスマホがよみがえったら、開発を支援できます：",
    links_title="リンク",
    l_site="ウェブサイト", l_channel="Telegram チャンネル", l_author="作者", l_orig="オリジナル作者",
    license_title="ライセンス",
    license_text="GPL-3.0。Android、商標、ファームウェアは各所有者に帰属します。",
)

T["ko"] = dict(
    s_fw="테스트된 펌웨어", s_langs="개 언어", s_to="~", copied="주소가 복사되었습니다",
    tagline="클래식 Android 펌웨어 — HTC Sense, TouchWiz, MIUI, AOSP — 를 최신 휴대폰에서. 루팅도 PC도 필요 없습니다.",
    about="AEmulator는 펌웨어 파일에서 진짜 Android 2.3–4.4 시스템을 바로 부팅합니다: 리커버리 ZIP, Odin 아카이브, Google 팩토리 이미지. 오래된 ARM 코드는 수정된 QEMU가 변환하고, 커널 binder를 에뮬레이션하며, 그래픽은 휴대폰 GPU로, 소리는 Android 오디오로 처리합니다. 모두 평범한 앱 안에서 동작합니다.",
    feat_title="기능",
    feats=["거의 모든 형식 가져오기: CWM/TWRP ZIP, 삼성 Odin `.tar.md5`, Google 팩토리 `.tgz`, `system.img`, OTA `system.new.dat.br`",
           "제조사 UI가 그대로 동작: HTC Sense, Samsung TouchWiz, MIUI, AOSP",
           "GL 브리지 하드웨어 그래픽, 소리, 터치와 멀티터치, 최신 TLS 프록시 네트워크",
           "APK·음악·사진을 위한 공유 메모리 카드 폴더",
           "18개 언어의 Material 3 Expressive 인터페이스",
           "무료 오픈 소스(GPL-3.0)"],
    fw_title="지원 펌웨어",
    fw_intro="Xiaomi 15(Snapdragon 8 Elite, Android 16)에서 테스트했습니다. Android 2.3–4.4용 32비트 ARM 펌웨어라면 시도해 볼 만합니다. 목록은 확인된 이미지만 담고 있습니다.",
    c_device="기기", c_android="Android", c_skin="UI", c_status="상태", c_download="다운로드",
    st_ok="동작", st_partial="일부", st_wip="작업 중", st_untested="미테스트", st_no="아직",
    n_sound="소리 동작", n_bt="Bluetooth 오류 창", n_nosound="아직 소리 없음", n_wip="설정 마법사까지 부팅, 안정화 중",
    n_lollipop="Android 5는 실험적", n_crash="비공식 포팅은 충돌", n_arm64="64비트 Android 7 — 계획된 arm64 엔진 필요",
    dl_rootfs="바로 가져올 수 있는 아카이브", dl_factory="Google 팩토리 이미지", dl_odin="Odin 패키지", dl_zip="리커버리 ZIP", dl_ftf="FTF 패키지",
    fw_legal="펌웨어 파일은 각 제조사의 것입니다. 링크는 제조사 서버나 공개 아카이브로 연결되며 AEmulator에는 펌웨어가 포함되지 않습니다.",
    start_title="빠른 시작",
    steps=["[Releases]({repo}/releases)에서 APK를 받아 설치합니다.",
           "위 표에서 펌웨어를 휴대폰으로 받습니다.",
           "AEmulator → **펌웨어 추가**에서 파일을 고릅니다. 가져오기는 몇 분 걸립니다.",
           "**시작**을 누릅니다. 첫 부팅은 앱 최적화로 더 오래 걸립니다.",
           "⋮ 메뉴에서 볼륨·전원 버튼·로그, ⚙️에서 설정과 언어."],
    req_title="요구 사항",
    reqs=["64비트 ARM 휴대폰(arm64-v8a)의 Android 8.0+", "펌웨어당 약 1–3GB 여유 공간", "최신 Snapdragon / Dimensity / Tensor 권장"],
    build_title="소스에서 빌드",
    build_text="JDK 17, Android SDK 36, NDK r28이 필요합니다. 게스트 라이브러리는 `native/*/build.sh`로 빌드합니다.",
    how_title="작동 방식",
    how_text="각 게스트 프로세스는 수정된 사용자 모드 QEMU에서 실행됩니다. binder 데몬이 커널 드라이버를 대신하고, GL 브리지가 OpenGL ES 호출을 GPU로 전달하며, 작은 게스트 라이브러리(오디오 HAL, audio policy 래퍼, LD_PRELOAD 심)가 제조사 코드를 에뮬레이터에 맞춥니다. 가져오기 도구는 펌웨어를 읽고 boot 이미지의 init 스크립트로 서비스 시작 계획을 만듭니다.",
    credits_title="감사의 말",
    credits_text="AEmulator는 [원작자]({orig})의 HTC Desire HD·HTC One M7 에뮬레이터에서 시작되었습니다. 그의 엔진이 없었다면 이 프로젝트도 없었습니다.",
    support_title="프로젝트 후원",
    support_text="AEmulator로 추억의 휴대폰을 되살렸다면 개발을 후원할 수 있습니다:",
    links_title="링크",
    l_site="웹사이트", l_channel="텔레그램 채널", l_author="제작자", l_orig="원작자",
    license_title="라이선스",
    license_text="GPL-3.0. Android, 상표, 펌웨어는 각 소유자에게 있습니다.",
)
